server:
  port: 80
  servlet:
    context-path: /mmdesk
  tomcat:
    uri-encoding: UTF-8

spring:
  name: mmdesk
  profiles:
    active: dev
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/mmwebdesktop?useAffectedRows=true&useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  mapper-locations: classpath:mybatis/mappers/**/*.xml       # mapper映射文件
mybatis-plus:
  mapper-locations: classpath:mybatis/mappers/**/*.xml       # mapper映射文件

# 打印sql
logging:
  path: ./mm-webDesktop/logs

#
#liv:
#  mapProps:
#    usecache: redis  #值为 redis / ehcache,使用 redis还是ehcache
#    user-login-fail-retry-times: 5   #用户登录失败重试次数
#    user-login-fail-locked-time: 10   #用户登录失败锁定时常(分钟)
#    user-login-timeouts: 1   #用户登录会话时常（分钟）
#    user-login-token-renewal-onaccess: true  #值为 true / false, 用户每次访问是重新生成 token,也就是token用一次即失效