server:
  port: 80
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: dev
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/auth?useAffectedRows=true&useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
#    cluster:
#      nodes:
#        - 127.0.0.1:6379
#        - 127.0.0.1:6380
#        - 127.0.0.1:6381
#        - 127.0.0.1:6382
    lettuce:
      pool:
        # 连接池中的最大空闲连接 默认8
        max-idle: 8
        # 连接池中的最小空闲连接 默认0
        min-idle: 0
        # 连接池最大连接数 默认8 ，负数表示没有限制
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-wait: -1
    timeout: 30000

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  mapper-locations: classpath:mybatis/mappers/**/*.xml       # mapper映射文件

token:
  #  token过期时间，单位分钟
  tokenExpireTime: 604800 # token有效时长，7天
  #  RefreshToken过期时间，单位：分钟, 24*60=1440
  #refreshTokenExpireTime: 1440
  #  shiro缓存有效期，单位分钟,2*60=120
  #shiroCacheExpireTime: 120
  #  token加密密钥
  secretKey: storywebkey
# 打印sql
logging:
  path: ./liv-auth/logs

liv:
  mapProps:
    usecache: redis  # redis  或者 ehcache,使用 redis还是ehcache
    log-fail-retry-times: 10   #用户登录失败重试次数
    user-login-timeouts: 30   #用户登录会话时常（分钟）